### ISSUE TITLE
"Resolving Layout Overlapping Issues in UmiJS/Max Sub-Apps"

### ISSUE THREAD

**Issue by duongkhang042001** [giscafer/micro-umi-max-cra#1]
When deploying a sub-app using UmiJS/Max, I'm encountering issues with layout overlapping. Can you please help me with this? The overlapping issue is quite bothersome, and I'm looking for a solution. Your assistance would be greatly appreciated.

![image](https://github.com/giscafer/micro-umi-max-cra/assets/63197900/55366fe2-0d14-4e89-af56-56a6b1506755)

Thank you for your help.

**Comment by duongkhang042001** [comment]
My English is not very good. I hope you can help me.

**Comment by giscafer** [comment]
see demo: https://github.com/giscafer/rh-template-gis
